name: Guivemetunes
favicon: null
layout_spectrum: 0.23038
typography_spectrum: 0.24377
title: 'Vibes, beats and tunes'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#616161'
    - '#fefefe'
    - '#979cce'
    - '#c0c4ec'
  brandStrength: 0.3125
  lightness: 0.2617021
  saturation: 0.6319149
  rhythmicContrast: 0.7127659
purpose: []
